// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmgtsqsfzbybdlxuytgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtZ3RzcXNmemJ5YmRseHV5dGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjQzNjQsImV4cCI6MjA3MTk0MDM2NH0.wldueS_roypg-g9BstCxH9FjPZ61xgRUB8WpzbaZxIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});